package service

import (
	"context"
	"testing"

	"github.com/user/financial-os/internal/model"
	"github.com/user/financial-os/internal/repository"
)

func TestAllocationService(t *testing.T) {
	setupTestEnv()

	userRepo := repository.NewUserRepository(testDB)
	efServ := NewEFService(testDB)
	forecastServ := NewForecastService(testDB, testRedis)
	allocationServ := NewAllocationService(testDB, forecastServ, efServ)

	ctx := context.Background()
	cleanDatabase(t)

	// Create test user
	testUser := &model.User{
		Email:        "allocator@example.com",
		PasswordHash: "hashedPassword",
		Name:         "Allocator Test",
		Role:         "owner",
		IsActive:     true,
	}
	var err error
	testUser, err = userRepo.CreateUser(ctx, testUser)
	if err != nil {
		t.Fatalf("failed to create test user: %v", err)
	}

	t.Run("Get allocation advice success", func(t *testing.T) {
		resp, err := allocationServ.GetAllocationAdvice(ctx, testUser.ID)
		if err != nil {
			t.Fatalf("failed to get allocation advice: %v", err)
		}

		if len(resp.Advices) == 0 {
			t.Error("expected advices to be generated by rule engine priority order")
		}
	})
}
